### ISSUE TITLE
JQuery Prevents Tests From Passing

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/your-own-js-and-css-in-rails#10] opened 2018-06-14 22:43 UTC
A number of these javascript libs include JQuery by default, but actually using any JQuery will often prevent the tests from passing, even if the code correctly implements the required features.

It may be best to simply remove JQuery from these labs if the tests are not going to be written to allow its use.

**Comment by sgharms** [comment] 2018-08-01 21:28
Hi @ecssiah,

I'm not sure i follow your issue. The lab is solvable by jQuery. I just wrote it from scratch here and things worked fine. Since I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed by sgharms** 2018-08-01 21:28 UTC

**Comment by sgharms** [comment] 2018-12-04 13:13
@Hector-Ariceaga I'm still able to pass this fine using jQuery only.

Looking at your ['Done' commit](https://github.com/Hector-Ariceaga/your-own-js-and-css-in-rails-v-000/commit/5ae442102870c4fe9abe205c153f3d32c0b93851), I don't see a committed file with a change in it (I'd have expected _something_ to change in `app/assets/javascripts/`).

As such, why don't you consider engaging an online coach to review your solution. Either they can help you get this working with jQuery or they can contact me to sort out any bugs.

Also: Please open new issues versus commenting on old issues. It's great to _reference_ the old one, but the notifications are better for new issues versus updates to old ones.
